### ISSUE TITLE
ERROR:Time-out waiting for eeschema, giving up

### ISSUE THREAD

**Issue by swissbyte** [INTI-CMNB/kicad_auto#11]
Hi 

im using this setup here: https://github.com/swissbyte/kicadtest

and im getting this error message: ERROR:Time-out waiting for eeschema, giving up

do you have an idea why this could happen?

thank you 😊

**Comment by set-soft** [comment]
You committed `#auto_saved_files#` IMHO a very bad idea.
And this file says KiCad had a couple of pending auto saves:
```
C:\code\KiCad\EduboardV2_Baseboard\_autosave-power.kicad_sch
C:\code\KiCad\EduboardV2_Baseboard\_autosave-connectors.kicad_sch
```
Which aren't available, so eeschema informs about this situation blocking the GUI.
Try removing this file. 
BTW: this is the result of a crash or committing before saving to disk
