### ISSUE TITLE
kicad7_auto:latest and problems with kikit

### ISSUE THREAD

**Issue by solent710** [INTI-CMNB/kicad_auto#12]
kikit from kicad7_auto: latest complains as below:

Gtk-Message: 21:30:19.301: Failed to load module "canberra-gtk-module"

The same version of kikit (1.3.0-7) installed on the host processes the same set of files without any problem.

**Comment by set-soft** [comment]
Don't worry about it, you don't need GTK stuff on a docker image that doesn't even connect to the X server. This is most probably KiKit initializing the wxApp (wxWidgets), which isn't necesary,
