### ISSUE TITLE
use new version of InteractiveHtmlBom

### ISSUE THREAD

**Issue by honzakutil** [INTI-CMNB/kicad_auto#18]
in docker image kicad7_auto_full:dab7a024aecb (latest at the time of writing this issue) is used plugin InteractiveHtmlBom version 2.7.0. This version has broken handling of kicad DNP field (configuration entry `dnp_field: 'kicad_dnp'` has no effect). This was fixed in later versions, it is working in v2.8.1. If I manually copy new version of plugin inside dunning docker image, configuration entry `dnp_field: 'kicad_dnp'` is working as expected.

Could you put new version of InteractiveHtmlBom to the docker image?

**Comment by set-soft** [comment]
Ok, I updated iBoM to 2.8.1
