### ISSUE TITLE
KiCad and library version mismatch in 1.6.4

### ISSUE THREAD

**Issue by Swij** [INTI-CMNB/kicad_auto#19]
In the latest `kicad_auto` release, which is 1.6.4, the main KiCad version and the library versions are not the same.
 
```
$ docker run -it ghcr.io/inti-cmnb/kicad7_auto:1.6.4 /bin/bash
root@51b1fee6c322:/# apt list kicad*
Listing... Done
kicad-footprints/now 7.0.9-0~ubuntu23.04.1 all [installed,local]
kicad-git-filters/now 1.0.1-1 all [installed,local]
kicad-symbols/now 7.0.9-0~ubuntu23.04.1 all [installed,local]
kicad-templates/now 7.0.9-0~ubuntu23.04.1 all [installed,local]
kicad/now 7.0.10~ubuntu23.04.1 amd64 [installed,local]
root@51b1fee6c322:/# 
```

I would expect the library version to be the same as KiCad (7.0.10) and not 7.0.9

In my case, this causes incorrect ERC warnings that don't appear when ERC is run manually in KiCad. 

e.g. `WARNING:(lib_symbol_issues) Symbol 'Buzzer' has been modified in library 'Device'`

**Comment by set-soft** [comment]
This is not an issue. On Debian some times KiCad gets a new version but the libs doesn't. Is normal.

The current problem is with the official KiCad repo, take a look at this file: 

https://ppa.launchpadcontent.net/kicad/kicad-7.0-releases/ubuntu/dists/lunar/main/binary-amd64/Packages.gz

All the  libs are 7.0.9.

Usually the libs doesn't even change. In this case you have a mismatch, so I guess something really changed. You should make your project self contained or disable such a check on CI/CD environments. I can generate a fresh image, but you'll face this problem again when the KiCad team releases a Debian/Ubuntu package and the libs are packaged days before.

Again: this check is very particular and helps in very particular cases.

I'm creating images using "Lunar" binaries and "Mantic" libs, should fix your issue.
