### ISSUE TITLE
eeschema_do Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by AntaeusNar** [INTI-CMNB/kicad_auto#4]
Running the following command:
`eeschema_do run_erc <MY_SCHEMATIC> <MY_REPORT_FOLDER>`
generates:
`Segmentation fault (core dumped)`

Running:
`eeschema_do -h`
works as expected

Running:
`eeschema_do run_erc`
generates the missing parameters error as expected.

The docker run command is:
`$ docker run -t -d -u 1001:1001 -w /var/lib/jenkins/workspace/<MY_GITHUB_REPO> -v /var/lib/jenkins/workspace/<MY_GITHUB_REPO>:/var/lib/jenkins/workspace/<MY_GITHUB_REPO>:rw,z -v /var/lib/jenkins/workspace/<MY_GITHUB_REPO>@tmp:/var/lib/jenkins/workspace/<MY_GITHUB_REPO>@tmp:rw,z -e setsoft/kicad_auto:latest cat`
(Repo info has been sanitized)

I am using Jenkins 2.303.2 with a declarative Jenkinsfile Pipeline, running docker on Ubuntu 20.04.

**Comment by set-soft** [comment]
Hi @AntaeusNar !
I never had the chance to try using Jenkins, the current version changed a lot, so I'm closing this report
